((nil . ((enh-ruby-indent-level . 2)
         (ruby-indent-level . 2)
         (js-indent-level . 2)
         (js2-basic-offset . 2)
         (prelude-clean-whitespace-on-save . nil)
         (fill-column . 120))))
