guard 'jasmine' do
  watch(%r{app/assets/javascripts/(.+).(js|js.coffee)}) { |m| "spec/javascripts/#{m[0]}_spec.#{m[1]}" }
  watch(%r{spec/javascripts/(.+)_spec.(js|js.coffee)})  { "spec/javascripts/#{m[0]}_spec.#{m[1]}" }
  watch(%r{spec/javascripts/spec.(js|js.coffee)})       { "spec/javascripts" }
end
